#!/usr/bin/env node
const dotenv = require('dotenv').config({ path: './../.env' })
const program = require('commander')
const logger = require('./../lib/logger')
const charges = require('./../utils/charges')

// NOTE: transfer net eventually ran into a corner case where we couldn't transfer
// the net amount from platform to Connect because of insufficient funds in the
// platform, this was likely because of not turning of payouts on the Platform
// account and not correctly setting source_transaction, this should be proven
const METHODS = {
  TRANSFER_NET: { charge: charges.create, refund: charges.refund },
  DEBIT_FEE: { charge: charges.createDebitFee, refund: charges.refundDebitFee }
}
const method = METHODS.DEBIT_FEE

// any options (none set) are passed into cmd
const requestNewCharge = async function requestNewCharge (amount, cmd) {
  logger.info(`[scripts/stripe] Create new charge request for ${amount}`)
  try {
    const result = await method.charge(amount, cmd.available)
    logger.info(`[scripts/stripe] New charge created ${result.charge.id}`)
  } catch (error) {
    logger.error('[scripts/stripe] Charge request failed ', error)
  }
}

const requestRefund = async function requestRefund (chargeID, amount, cmd) {
  logger.info(`[scripts/stripe] Requesting refund for charge ${chargeID}`)
  try {
    const result = await method.refund(chargeID, amount)
    logger.info(`[scripts/stripe] Refund completed ${result.refund.id}`)
  } catch (error) {
    logger.error('[scripts/stripe] Refund request failed ', error)
  }
}

program
  .version('1.0.0')

program
  .command('charge <amount>')
  .option('-a, --available', 'Make funds immediately available')
  .action(requestNewCharge)

program
  .command('refund <chargeID> [amount]')
  .action(requestRefund)

program.parse(process.argv)
